config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'all', to: "notes#all"
  get 'random', to: 'notes#random'

  resources :notes

  root 'notes#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord

  has_many :notes
  # profanity_filter :body, :method => 'vowels'

  validates :body, presence: true, length: {minimum: 1, maximum: 400}

  def to_param
    id.to_s + "-" + body.parameterize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @note = Note.new
    @featured_notes = Note.where(is_featured: true)
  end


  def all
    @notes = Note.all
  end


  def random
    @note = Note.order('RANDOM()').first
  end


  def create
    @note = Note.new(form_params)
    @featured_notes = Note.where(is_featured: true)

    if @note.save
      flash[:success] = "Your note has been submitted!"
      if session[:notes].present?
        session[:notes].push(@note.id)
      else
        session[:notes] = [@note.id]
      end
      redirect_to root_path
    else
      render "index"
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def show
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(form_params)
      redirect_to note_path(@note)
      flash[:success] = 'Your note has been updated!'
    else
      render "edit"
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    redirect_to random_path
    flash[:success] = 'Your note has been deleted!'
  end

  def form_params
    params.require(:note).permit(:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leave A Note</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= display_meta_tags site: 'Leave A Note' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <% if flash[:success].present?%>
      <div class="success">
        <%= flash[:success]%>
      </div>
    <% end %>

    <% if flash[:error].present?%>
      <div class="error">
        <%= flash[:error]%>
      </div>
    <% end %>
    <%= yield %>

    <%= javascript_include_tag 'application' %>


  </body>
</html>

app/views/notes/_createnote.html.erb
<div class="note">
  <%= simple_form_for @note do |f| %>
    <%= f.input :body, placeholder: 'Say something...', label: false %>
    <%= f.submit 'Save Note' %>
  <% end %>
</div>

app/views/notes/_footer.html.erb
<footer>
  <div class="container">
    <%= link_to 'New Note', root_path%>
    <%= link_to 'All Notes', all_path%>
    <%= link_to 'Random Note', random_path%>
    <%= link_to 'Briana Gude', "http://www.brianagude.com/", target: :_blank%>
  </div>
</footer>

app/views/notes/_shownote.html.erb
  <div class="shownote">
    <h1><%= simple_format @note.body%></h1>
  </div>

  <footer>
    <div class="container">
      <% if session[:notes].present? and session[:notes].include?(@note.id)%>
        <div class="actions">
            <%= link_to "Edit this note", edit_note_path(@note)%>
            <p>Created <%= time_ago_in_words @note.created_at %> ago</p>
            <%= link_to "Delete this note", note_path(@note), method: :delete, data: {confirm: "Are you sure??"} %>
        </div>
      <% else %>
        <div class="show">
          <p>Created <%= time_ago_in_words @note.created_at %> ago</p>
        </div>
      <% end %>
    </div>
  </footer>

app/views/notes/all.html.erb
  <header>
    <div class="container">
      <%= link_to 'Random', random_path%>
      <%# <h1><%= link_to 'Home', root_path%></h1> %>
      <h3>Leave A Note</h3>
      <%= link_to 'New', root_path%>
    </div>
  </header>

  <div class="allnotes">
    <% @notes.order('created_at desc').each do |note| %>

      <%=link_to note_path(note) do %>
        <div class="notes desktop">
          <h2> <%= simple_format truncate(note.body, :length => 100) %> </h2>
        </div>
        <div class="notes mobile">
          <h2> <%= simple_format truncate(note.body, :length => 25) %> </h2>
        </div>
      <% end %>

    <% end %>
  </div>

  <%= render 'footer' %>

app/views/notes/edit.html.erb
<header>
  <div class="container">
    <%= link_to 'New', root_path%>
    <h1> <%= title 'Edit' %></h1>
    <%= link_to 'All', all_path%>
    <h5>Edit</h5>
  </div>
</header>

<%= render 'createnote' %>

<footer>
  <div class="container">
    <div class="actions">
      <%= link_to 'Random Note', random_path%>
      <p>Created <%= time_ago_in_words @note.created_at %> ago</p>
      <%= link_to "Delete this note", note_path(@note), method: :delete, data: {confirm: "Are you sure??"}%>
    </div>
  </div>
</footer>

app/views/notes/index.html.erb
<header>
  <div class="container">
    <%= link_to 'Random', random_path%>
    <h2> <%= title 'Leave A Note' %></h2>
    <%= link_to 'All', all_path%>
  </div>
</header>

<%= render 'createnote' %>
<%= render 'footer' %>

app/views/notes/rand.html.erb
  <header>
    <%= link_to 'Random Note', rand_path, :class => "effect-shine" %>
    <%= link_to 'Leave A Note', root_path, :class => "effect-shine" %>
    <%= link_to 'View All Notes', all_path, :class => "effect-shine" %>
  </header>

  <%= render 'shownote' %>

app/views/notes/random.html.erb
  <header>
    <div class="container">
      <%= link_to 'Random', random_path%>
      <%= link_to 'New', root_path%>
      <%= link_to 'All', all_path%>
      <h5>Leave A Note</h5>
    </div>
  </header>

  <%= render 'shownote' %>

app/views/notes/show.html.erb
  <header>
    <div class="container">
      <%= link_to 'Random', random_path%>
      <%= link_to 'New', root_path%>
      <%= link_to 'All', all_path%>
      <h5>Leave A Note</h5>
    </div>
  </header>

  <%= render 'shownote' %>